services:
  # PostgreSQL Database
  db:
    image: postgres:17-alpine
    container_name: portal-services-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: portalservicesdb
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./appserver/database/init:/docker-entrypoint-initdb.d
    networks:
      - portal-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d portalservicesdb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Portal Services API Server
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portal-services-api
    restart: unless-stopped
    env_file:
      - ./appserver/docker.env
    ports:
      - "3001:3001"
    volumes:
      - ./appserver/logs:/app/logs
    networks:
      - portal-network
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=portalservicesdb
      - DB_USER=admin
      - DB_PASSWORD=admin

volumes:
  postgres_data:
    driver: local

networks:
  portal-network:
    driver: bridge
