[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
cmds = [
  "npm ci",
  "cd appserver && npm ci",
  "cd ../appclient && npm ci --legacy-peer-deps"
]

[phases.build]
cmds = [
  "cd appserver && npm run build",
  "cd ../appclient && npm run build"
]

[start]
cmd = "cd appserver && npm start"
