[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = [
  "npm ci --silent",
  "cd appserver && npm ci --silent",
  "cd ../appclient && npm ci --legacy-peer-deps --silent"
]

[phases.build]
cmds = [
  "echo '🚀 Railway Build - Portal Services'",
  "npm run typecheck",
  "cd appserver && npm run railway:build",
  "cd ../appclient && npm run railway:build",
  "echo '✅ Railway build completed successfully'"
]

[start]
cmd = "npm run railway:start"
