version: '3.8'

services:
  postgres_db:
    image: postgres:latest
    container_name: postgres_portalservices
    environment:
      POSTGRES_DB: portalservicesdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: