databases:
  - name: portalservices-db
    databaseName: portalservicesdb
    user: admin
    plan: free

services:
  - type: web
    name: portal-services-api
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DB_HOST
        fromDatabase:
          name: portalservices-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: portalservices-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: portalservices-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: portalservices-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: portalservices-db
          property: password
      - key: DATABASE_URL
        fromDatabase:
          name: portalservices-db
          property: connectionString