services:
  - type: pserv
    name: portalservices-database
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: POSTGRES_DB
        value: portalservicesdb
      - key: POSTGRES_USER
        value: admin
      - key: POSTGRES_PASSWORD
        generateValue: true
      - key: POSTGRES_HOST_AUTH_METHOD
        value: trust
    disk:
      name: postgres-data
      mountPath: /var/lib/postgresql/data
      sizeGB: 10
    healthCheckPath: /health
