services:
  - type: web
    name: portal-services-frontend
    runtime: static
    env: static
    region: oregon
    buildCommand: npm ci --legacy-peer-deps && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: https://portal-services-backend.onrender.com
      - key: REACT_APP_VERSION
        value: 3.1.0
      - key: REACT_APP_ENVIRONMENT
        value: production
      - key: GENERATE_SOURCEMAP
        value: false
      - key: CI
        value: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        headers:
          X-Frame-Options: DENY
          X-Content-Type-Options: nosniff
          Referrer-Policy: strict-origin-when-cross-origin
          Permissions-Policy: camera=(), microphone=(), geolocation=()
      - path: /static/*
        headers:
          Cache-Control: public, max-age=31536000, immutable
